<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MITMSpec.Worker-526e6714-3018-4edf-89ee-e27e8d0834dd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MITMSpec.Application\MITMSpec.Application.csproj" />
    <ProjectReference Include="..\MITMSpec.Infrastructure\MITMSpec.Infrastructure.csproj" />
    <ProjectReference Include="..\MITMSpec.Contracts\MITMSpec.Contracts.csproj" />
  </ItemGroup>
</Project>
